"use client";
import {useEffect,useRef,useState} from "react";
import type {Track,Point,Run} from "@/lib/types";
import {formatTime,progressRace,type RaceState} from "@/lib/racing";
import {getName,savePB,saveName} from "@/lib/storage";
export default function PlayerRun({track,onPositionChange,onRaceStateChange}:{track:Track;onPositionChange?:(point:Point)=>void;onRaceStateChange?:(state:RaceState)=>void}){const [name,setName]=useState("");const [message,setMessage]=useState("Set your name, then start when you are inside the green start zone.");const [state,setState]=useState<RaceState>({phase:"ready",nextCheckpoint:0,sequence:[]});const [accuracy,setAccuracy]=useState<number|undefined>(undefined);const watch=useRef<number|undefined>(undefined);const maxSpeed=useRef(0);const interval=useRef<ReturnType<typeof setInterval>|undefined>(undefined); const [now,setNow]=useState(Date.now());
 useEffect(()=>setName(getName()),[]);useEffect(()=>{if(state.phase==="racing"){interval.current=setInterval(()=>setNow(Date.now()),100)}else if(interval.current)clearInterval(interval.current);return()=>{if(interval.current)clearInterval(interval.current)}},[state.phase]);
 const stop=()=>{if(watch.current!==undefined)navigator.geolocation.clearWatch(watch.current);watch.current=undefined};
 const submit=async(s:RaceState)=>{if(!s.elapsedMs)return;const payload:Run={trackId:track.id,displayName:name.trim(),elapsedMs:s.elapsedMs,accuracyM:accuracy||999,maxSpeedMps:maxSpeed.current,gateSequence:s.sequence};savePB(track.id,s.elapsedMs);try{const r=await fetch("/api/runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error);setMessage("Lap saved locally and submitted to the all-time board.")}catch(e){setMessage(`Lap saved locally. Leaderboard submission failed: ${e instanceof Error?e.message:"unknown error"}`)}finally{stop()}};
 const start=()=>{if(!name.trim()){setMessage("Enter a display name first.");return}if(!navigator.geolocation){setMessage("This browser does not support GPS location.");return}saveName(name);setMessage("Finding a precise GPS signal — move inside the green start zone to arm your lap.");const initial:RaceState={phase:"ready",nextCheckpoint:0,sequence:[]};stateRef.current=initial;setState(initial);onRaceStateChange?.(initial);maxSpeed.current=0;watch.current=navigator.geolocation.watchPosition(p=>{const current={lat:p.coords.latitude,lng:p.coords.longitude};onPositionChange?.(current);setAccuracy(p.coords.accuracy);if(p.coords.accuracy>75){setMessage("GPS accuracy is too low. Move to open sky and wait for ≤75 m.");return}if(p.coords.speed&&p.coords.speed>maxSpeed.current)maxSpeed.current=p.coords.speed;const next=progressRace(stateRef.current,current,track.startGate,track.checkpoints,Date.now());stateRef.current=next;setState(next);onRaceStateChange?.(next);if(next.phase==="ready")setMessage(next.startArmed?"Lap armed — leave the green start zone to begin timing.":"Move inside the green start zone to arm your lap.");if(next.phase==="racing")setMessage(next.nextCheckpoint<track.checkpoints.length?next.checkpointEntered?`Checkpoint ${next.nextCheckpoint+1} reached — leave its zone to count it.`:`Enter checkpoint ${next.nextCheckpoint+1} of ${track.checkpoints.length}, then leave its zone.`:"All checkpoints cleared — enter the green finish zone!");if(next.phase==="complete")submit(next)},e=>{setMessage(e.code===1?"Location permission was denied. Enable it and try again.":"GPS signal was lost. Your run was not submitted.");stop()},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})};
 const stateRef=useRef(state);useEffect(()=>{stateRef.current=state},[state]);const elapsed=state.phase==="complete"?(state.elapsedMs??0):state.startedAt?now-state.startedAt:0;
 return <section className="hud stack"><div className="row"><div><div className="eyebrow">{state.phase==="racing"?"Lap in progress":state.phase==="complete"?"Lap complete":"Ready"}</div><div className="time">{formatTime(elapsed)}</div></div><div className="muted">GPS {accuracy?`${Math.round(accuracy)}m`:"—"}</div></div><div className="status">{message}</div>{state.phase!=="racing"&&state.phase!=="complete"&&<><label className="stack"><span className="muted">Display name</span><input className="field" maxLength={32} value={name} onChange={e=>setName(e.target.value)} placeholder="Your race name"/></label><button className="btn" onClick={start}>Start GPS run</button></>}{state.phase==="racing"&&<button className="btn secondary" onClick={()=>{stop();setState({phase:"ready",nextCheckpoint:0,sequence:[]});setMessage("Run ended. No time was submitted.")}}>End run</button>}<p className="muted" style={{margin:0,fontSize:12}}>Location samples stay only in this browser during your run. GPS needs HTTPS and open sky.</p></section>}
